site_name: "การสร้างรายงานด้วย Looker Studio"
site_description: "คู่มือเชิงปฏิบัติการสร้าง Dashboard โดยใช้ Looker Studio"
site_url: "https://weeix.github.io/looker-studio-manual"
repo_url: "https://github.com/weeix/looker-studio-manual"
repo_name: "looker-studio-manual"
theme:
  name: material
  language: th
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: blue
extra_css:
  - assets/pdf-font.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - to-pdf:
      cover_subtitle: "คู่มือประกอบการฝึกปฏิบัติ"
      author: "วีร์ ศรีทิพโพธิ์"
      copyright: "© 2568 กองการอนุญาต กรมป่าไม้"
      toc_title: "สารบัญ"
      output_path: "pdf/looker-studio-workshop.pdf"
      download_link: header
      # debug_html: true
nav:
  - บทนำ: index.md
  - Workshop 1: workshop-1.md
  - Workshop 2: workshop-2.md
  - Workshop 3: workshop-3.md
  - Workshop 4: workshop-4.md
  - Workshop เสริมที่ 1: workshop-supplement-1.md
  - Workshop เสริมที่ 2: workshop-supplement-2.md
  - Workshop เสริมที่ 3: workshop-supplement-3.md
